services:
  web:
    build:
      context: ./backend
    container_name: autofillpro-api
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  celery_worker:
    build:
      context: ./backend
    container_name: autofillpro-celery
    command: celery -A app.celery.tasks worker --loglevel=info
    volumes:
      - ./backend:/code
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - web

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./package
      args:
        NEXT_PUBLIC_API_URL: /api
      
    container_name: autofill-frontend
    ports:
      - "3000:3000"
    env_file:
    - ./package/.env.production
    depends_on:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - web