name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # ✅ Will run on every push to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}  # ✅ MUST be the full private key (NOT .pub)

      - name: Deploy to server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /app/ProAutoFill
            git pull origin master
            docker compose down
            docker compose build --no-cache
            docker compose up -d
          EOF
